### ISSUE TITLE
External SD card exfat SELinux denials

### ISSUE THREAD

**Issue by mrjoel** [omnirom/android_device_motorola_potter#9]
In running the official omni-9-20190203 ROM for potter, and getting the following audit messages via logcat. 

I am running into issues processing the exFAT filesystem on an inserted external SD card. The card works fine on OmniROM 8.x, and is read file from TWRP. I've collected several audit entries together below. Running the system is very unstable with this SD card inserted, even trying to run the Files app or Camera terminates the application. I get frequent popup messages indicating "android.process.media keeps stopping" and "Bluetooth keeps stopping" among others. From other sections in the logs it seems likely that it's due to the volume being notified, but containing a null path value and point of use not checking for null in the string.

02-09 18:04:26.177  4501  4501 W sgdisk  : type=1400 audit(0.0:5910): avc: denied { noatsecure } for uid=0 scontext=u:r:vold:s0 tcontext=u:r:sgdisk:s0 tclass=process permissive=0

02-09 18:04:26.213  4502  4502 W sh      : type=1400 audit(0.0:5911): avc: denied { noatsecure } for uid=0 scontext=u:r:vold:s0 tcontext=u:r:blkid_untrusted:s0 tclass=process permissive=0

02-09 18:04:26.283  4503  4503 W Binder:456_3: type=1400 audit(0.0:5912): avc: denied { entrypoint } for uid=0 path="/system/bin/mount.exfat" dev="mmcblk0p53" ino=656 scontext=u:r:fsck_untrusted:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
02-09 18:04:26.282   456   460 V vold    :     /dev/block/vold/public:179,65
02-09 18:04:26.286  4503  4503 E logwrapper: executing /system/bin/fsck.exfat failed: Permission denied
02-09 18:04:26.287   456   460 I fsck.exfat: executing /system/bin/fsck.exfat failed: Permission denied
02-09 18:04:26.290   456   460 I fsck.exfat: fsck.exfat terminated by exit(255)
02-09 18:04:26.291   456   460 E vold    : Check failed (code 255)
02-09 18:04:26.291   456   460 E vold    : public:179,65 failed filesystem check
02-09 18:04:26.292   669  1019 E StorageManagerService: 
02-09 18:04:26.292   669  1019 E StorageManagerService: android.os.ServiceSpecificException:  (code -5)
02-09 18:04:26.292   669  1019 E StorageManagerService:         at android.os.Parcel.createException(Parcel.java:1964)
02-09 18:04:26.292   669  1019 E StorageManagerService:         at android.os.Parcel.readException(Parcel.java:1918)
02-09 18:04:26.292   669  1019 E StorageManagerService:         at android.os.Parcel.readException(Parcel.java:1868)
02-09 18:04:26.292   669  1019 E StorageManagerService:         at android.os.IVold$Stub$Proxy.mount(IVold.java:773)
02-09 18:04:26.292   669  1019 E StorageManagerService:         at com.android.server.StorageManagerService$StorageManagerServiceHandler.handleMessage(StorageManagerService.java:622)
02-09 18:04:26.292   669  1019 E StorageManagerService:         at android.os.Handler.dispatchMessage(Handler.java:106)
02-09 18:04:26.292   669  1019 E StorageManagerService:         at android.os.Looper.loop(Looper.java:193)
02-09 18:04:26.292   669  1019 E StorageManagerService:         at android.os.HandlerThread.run(HandlerThread.java:65)
02-09 18:04:26.293  1422  1422 D StorageNotification: Notifying about public volume: VolumeInfo{public:179,65}:
02-09 18:04:26.293  1422  1422 D StorageNotification:     type=PUBLIC diskId=disk:179,64 partGuid= mountFlags=VISIBLE mountUserId=0 
02-09 18:04:26.293  1422  1422 D StorageNotification:     state=UNMOUNTABLE 
02-09 18:04:26.293  1422  1422 D StorageNotification:     fsType=exfat fsUuid=0000-0000 fsLabel=disk 
02-09 18:04:26.293  1422  1422 D StorageNotification:     path=null internalPath=null

**Comment by mrjoel** [comment]
I subsequently confirmed that when running SELinux in permissive mode the exFAT volume is successfully mounted, after the exfatfsck takes place.

**Comment by mrjoel** [comment]
I've filed this on the device specific repo, but after looking further it may not be a device specific item. If I need to report this issue at a different location, please let me know where a better, more general location would be.

**Comment by ifForeverlove** [comment]
You can put these things into a file ,for example 1.txt
After that run audit2allow -i 1.txt ,you got these.

allow vold blkid_untrusted:process noatsecure;
allow vold sgdisk:process noatsecure;
allow fsck_untrusted system_file:file entrypoint;

Put them into X.te file.
02-09 18:04:26.177 4501 4501 W sgdisk : type=1400 audit(0.0:5910): avc: denied { noatsecure } for uid=0 scontext=u:r:vold:s0 tcontext=u:r:sgdisk:s0 tclass=process permissive=0

02-09 18:04:26.213 4502 4502 W sh : type=1400 audit(0.0:5911): avc: denied { noatsecure } for uid=0 scontext=u:r:vold:s0 tcontext=u:r:blkid_untrusted:s0 tclass=process permissive=0

02-09 18:04:26.283 4503 4503 W Binder:456_3: type=1400 audit(0.0:5912): avc: denied { entrypoint } for uid=0 path="/system/bin/mount.exfat" dev="mmcblk0p53" ino=656 scontext=u:r:fsck_untrusted:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
